### ISSUE TITLE
Make UX Changes to the Prototype

### ISSUE THREAD

**Issue by bsmithgall** [codeforamerica/template-maker#21]
## Copy
- See results of #20 
- Blank sections to named sections
## Open questions
- How can we make this closer to the click-through prototype?
## TODO
- [x] Focus on completing text section interaction
- [x] Work on #20 and integrate results into template copy
- [x] Integrate any design/UX pieces attached below from @shellicious / @hamhands

**Comment by bsmithgall** [comment]
Sneak preview:

![screen shot 2015-03-15 at 11 10 08 pm](https://cloud.githubusercontent.com/assets/1957344/6661370/7268e5d4-cb68-11e4-88eb-ceeb3938e68b.png)

**Comment by bsmithgall** [comment]
TODO from meeting March 17:
- [x] Add new template button in the template list view
- [x] New text sections should autofocus the editor
- [x] Variable styles are screwy and need to be fixed
- [x] Variable adding still has some weird problems when at the end of the available text (NOTE: You can't easily "focus" at the place that the cursor _was_ I don't think, so people are just going to have to click to focus after adding a variable for now.)
- [x] Flash a "saved"
- [x] Accordion doesn't work on non-editable view
- [x] Add an "instructions for bidders" button
- [x] Change "currently editing" to another save link/form submission
- [x] Draggable on "preview" section
- [x] Draggable icon on section edit for testing

**Comment by bsmithgall** [comment]
TODO from meeting March 18:
- [x] Allow moveable sections in edit view
- [x] Add number/bulleted lists to :icecream: :koala: 
- [x] Remove edit, start accordions open to preview page
- [x] Add template title, go back to editing to preview page 
- [x] Fix generator styles for variables
- [x] Add title and go back to editing button on generate page

**Comment by bsmithgall** [comment]
TODO from meeting May 19:
- [x] Boilerplate HTML copy
