### ISSUE TITLE
TODO for 4/8

### ISSUE THREAD

**Issue by bsmithgall** [codeforamerica/template-maker#37]
- [x] View for "currently working on contracts"
- [x] Delete in-progress documents
- [x] Actually break things out into sections as opposed to all on one page (separate branch)
- [x] ~~Add scrollspy for a full document view~~ [WONTFIX]
- [x] Save actually saves
- [x] Write tests
- [ ] Insert professional services agreement text
